// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHjN1oUjnoxHijGv674Xhg_M5wxmaHr4A',
    appId: '1:306292522034:web:b24c6b82a0afacac76902b',
    messagingSenderId: '306292522034',
    projectId: 'chatapp-b068a',
    authDomain: 'chatapp-b068a.firebaseapp.com',
    storageBucket: 'chatapp-b068a.appspot.com',
    measurementId: 'G-3HXH7WPYNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqtUtx9QlvZA3yr3EC_z288Sp1dAflWQw',
    appId: '1:306292522034:android:2fe2b34ce991182e76902b',
    messagingSenderId: '306292522034',
    projectId: 'chatapp-b068a',
    storageBucket: 'chatapp-b068a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7LYB8_woFRhnTpHqN5PuKe-b78rha34Y',
    appId: '1:306292522034:ios:290fcf7cdb82dab776902b',
    messagingSenderId: '306292522034',
    projectId: 'chatapp-b068a',
    storageBucket: 'chatapp-b068a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7LYB8_woFRhnTpHqN5PuKe-b78rha34Y',
    appId: '1:306292522034:ios:290fcf7cdb82dab776902b',
    messagingSenderId: '306292522034',
    projectId: 'chatapp-b068a',
    storageBucket: 'chatapp-b068a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHjN1oUjnoxHijGv674Xhg_M5wxmaHr4A',
    appId: '1:306292522034:web:cc2a82a246de6f2076902b',
    messagingSenderId: '306292522034',
    projectId: 'chatapp-b068a',
    authDomain: 'chatapp-b068a.firebaseapp.com',
    storageBucket: 'chatapp-b068a.appspot.com',
    measurementId: 'G-L3HHJBKQJ0',
  );
}
